"""add duo push method

Revision ID: 6f542023f57e
Revises: 1434aa7ed47c
Create Date: 2025-11-06 08:23:42.181054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f542023f57e'
down_revision = '1434aa7ed47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config') as batch_op:
        batch_op.add_column(sa.Column('duo_push_akey', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('duo_push_pkey', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('duo_push_host', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('duo_push_rsa_key_path', sa.VARCHAR(length=250), nullable=True))
        batch_op.add_column(sa.Column('duo_device', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config') as batch_op:
        batch_op.drop_column('duo_device')
        batch_op.drop_column('duo_push_rsa_key_path')
        batch_op.drop_column('duo_push_host')
        batch_op.drop_column('duo_push_pkey')
        batch_op.drop_column('duo_push_akey')
    # ### end Alembic commands ###
