name: Publish to PyPI

on:
  release:
    types: [published]
    tags:
      - 'v*'

jobs:
  test:
    name: Test SynackAPI Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Initialize Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: pip
      - name: Install package and test dependencies
        run: python -m pip install -e '.[dev]'
      - name: Lint SynackAPI with Flake8
        run: flake8 src test
      - name: Check plugin documentation
        run: python tools/check_docs.py
      - name: Run Unit Tests
        run: coverage run --source=src --omit='src/synack/db/alembic/env.py,src/synack/db/alembic/versions/*.py' -m unittest discover test
      - name: Check Coverage
        run: coverage report --fail-under=100
  publish:
    name: Build and Publish SynackAPI Package
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Inject version from Tag
        run: sed -i 's/version="[0-9.]*"/version="'${GITHUB_REF#refs/*/v}'"/' setup.py
      - name: Initialize Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: pip
      - name: Install build backend
        run: python -m pip install build
      - name: Build binary wheel and source tarball
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
